Repository stackabletech/agent, pull requests merged in 2021-03, with the labels that each got.

#91 Dependabot ignore kube*
  .github/dependabot.yml
Labels: type: enhancement

#78 Adds building and publishing of nightly deb package.
  .github/workflows/nightly.yml
  Cargo.lock
  Cargo.toml
  packaging/config/agent.conf
  packaging/debian/postinst
  packaging/debian/service
Labels: type: enhancement

#113 Revert "Bump reqwest from 0.10.9 to 0.11.2 (#103)"
  Cargo.lock
  Cargo.toml
Labels: type: bug

#127 Upgrade dependencies
  Cargo.lock
  Cargo.toml
  src/bin/agent.rs
  src/provider/error.rs
  src/provider/mod.rs
  src/provider/repository/repository_spec.rs
  src/provider/states/pod/running.rs
  src/provider/states/pod/setup_failed.rs
  src/provider/states/pod/starting.rs
  src/provider/systemdmanager/systemdunit.rs
Labels: dependencies, rust
